export default {
  ADD_PIZZA_CART: "ADD_PIZZA_CART",
  REMOVE_PIZZA_CART: "REMOVE_PIZZA_CART",
  PLUS_PIZZA_CART: "PLUS_PIZZA_CART",
  MINUS_PIZZA_CART: "MINUS_PIZZA_CART",
  CLEAR_CART: "CLEAR_CART",
  FETCH_PIZZAS: "FETCH_PIZZAS",
  SET_PIZZAS: "SET_PIZZAS",
  SET_CATEGORY: "SET_CATEGORY",
  SET_SORT_BY: "SET_SORT_BY",
}
